<?php
/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_postfinance_eFinance_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['postfinance_eFinance'] = array(
    'base' => 'commerce_postfinance_eFinance',
    'title' => t('e-Finance'),
    'short_title' => t('Postfinance e-Finance'),
    'description' => t('Postfinance e-Finance'),
    'terminal' => FALSE,
    'offsite' => TRUE,
  );

  return $payment_methods;
}

/**
 * Payment method callback: settings form.
 */
function commerce_postfinance_eFinance_settings_form($settings = NULL) {

	return commerce_postfinance_settings_form($settings);
}


function commerce_postfinance_eFinance_redirect_form($form, &$form_state, $order, $payment_method) {

	$payment_method['settings']['PM'] = 'PostFinance e-finance';
	/*$payment_method['settings']['BRAND'] = 'PostFinance e-finance';*/
	
	return commerce_postfinance_redirect_form($form, $form_state, $order, $payment_method);
}