<?php
/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_postfinance_VISA_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['postfinance_VISA'] = array(
    'base' => 'commerce_postfinance_VISA',
    'title' => t('VISA'),
    'short_title' => t('VISA'),
    'description' => t('VISA'),
    'terminal' => FALSE,
    'offsite' => TRUE,
  );

  return $payment_methods;
}

/**
 * Payment method callback: settings form.
 */
function commerce_postfinance_VISA_settings_form($settings = NULL) {

	return commerce_postfinance_settings_form($settings);
}


function commerce_postfinance_VISA_redirect_form($form, &$form_state, $order, $payment_method) {

	$payment_method['settings']['PM'] = 'CreditCard';
	$payment_method['settings']['BRAND'] = 'VISA';
	
	return commerce_postfinance_redirect_form($form, $form_state, $order, $payment_method);
}